# This workflow will install Python dependencies and lint with a single version of Python

name: pylint score

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pyyaml sqlalchemy flask
      - name: Run linting
        run: |
          scripts/verify-style.sh > linting.txt
      - name: Archive linting report
        uses: actions/upload-artifact@v2
        with:
          name: linting-report
          path: |
            linting.txt
